# Options for analysis running.
run:
  concurrency: 2
  timeout: 10m
  tests: true
  modules-download-mode: readonly
  go: '1.20'
linters:
  #disable-all: false
  #enable-all: true
  enable:
    - bidichk
    - bodyclose
    - containedctx
      #- cyclop
      #- dupl
    - exportloopref
    - gocritic
    - goconst
    - gosec
    - misspell
    - nilerr
    - paralleltest
    - prealloc
    - unparam
    - usestdlibvars
    - wastedassign
linters-settings:
  govet:
    # Report about shadowed variables.
    # Default: false
    check-shadowing: false
    # Settings per analyzer.
    #settings:
      # Analyzer name, run `go tool vet help` to see all analyzers.
    disable-all: false
    enable-all: true
    disable: 
      - shadow
      - fieldalignment # giving false positives
