version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: radeon_exporter
    main: ./
    binary: radeon_exporter
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.build={{.Version}}
      - -X go.szostok.io/version.version={{.Version}}
      - -X go.szostok.io/version.buildDate={{.Date}}
    goos:
      - linux

    goarch:
      - amd64
      - arm64

release:
  github:
    owner: kmulvey
    name: radeon_exporter
  # Whether to remove existing draft releases with the same name before creating
  replace_existing_draft: true
  # Whether to remove an artifact that already exists.
  replace_existing_artifacts: true
      
archives:
  - id: dist
    builds:
      - radeon_exporter
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - radeon_exporter.service
      - LICENSE
      - grafana-config.json
      
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

nfpms:
  # note that this is an array of nfpm configs
  - # ID of the nfpm config, must be unique.
    id: radeon_exporter

    package_name: radeon_exporter

    builds:
      - radeon_exporter

    # Your app's vendor.
    vendor: Kevin Mulvey

    # Your app's homepage.
    homepage: https://github.com/kmulvey/radeon_exporter

    # Your app's maintainer (probably you).
    maintainer: Drummer <drum-roll@example.com>

    # Your app's description.
    description: |-
      Prometheus exporter for Radeon (AMD) graphics cards.

    # Your app's license.
    license: MIT

    # Formats to be generated.
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux

    provides:
      - radeon_exporter

    # Path that the binaries should be installed.
    # Default: '/usr/bin'
    bindir: /usr/bin

    contents:
      # Basic file that applies to all packagers
      - src: radeon_exporter.service
        dst: /etc/systemd/system/radeon_exporter.service

    # Custom configuration applied only to the RPM packager.
    rpm:
      group: root
      compression: lzma
      # The package is signed if a key_file is set
      #signature:
      # PGP secret key file path (can also be ASCII-armored).
      # The passphrase is taken from the environment variable
      # `$NFPM_ID_RPM_PASSPHRASE` with a fallback to `$NFPM_ID_PASSPHRASE`,
      # where ID is the id of the current nfpm config.
      # The id will be transformed to uppercase.
      # E.g. If your nfpm id is 'default' then the rpm-specific passphrase
      # should be set as `$NFPM_DEFAULT_RPM_PASSPHRASE`
      #
      # Templates: allowed
      #key_file: "/home/kmulvey/keys/sec.gpg"
