{
 "title": "Radeon Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cardID",
    "query": {
     "query": "label_values(radeon_exporter_gpu_busy_percent,card_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Busy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radeon_exporter_gpu_busy_percent{card_id=\"$cardID\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRAM Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radeon_exporter_mem_busy_percent{card_id=\"$cardID\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overal Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "radeon_exporter_gpu_busy_percent{card_id=\"$cardID\"} ",
     "legendFormat": "GPU busy"
    },
    {
     "expr": "radeon_exporter_mem_busy_percent{card_id=\"$cardID\"} ",
     "legendFormat": "VRAM used"
    }
   ]
  },
  {
   "title": "VRAM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "radeon_exporter_mem_info_vis_vram_total{card_id=\"$cardID\"} ",
     "legendFormat": "Visible VRAM Total"
    },
    {
     "expr": "radeon_exporter_mem_info_vis_vram_used{card_id=\"$cardID\"} ",
     "legendFormat": "Visible VRAM Used"
    },
    {
     "expr": "radeon_exporter_mem_info_vram_used{card_id=\"$cardID\"} ",
     "legendFormat": "Total VRAM Used"
    },
    {
     "expr": "radeon_exporter_mem_info_vram_total{card_id=\"$cardID\"} ",
     "legendFormat": "Total VRAM"
    }
   ]
  },
  {
   "title": "Clock Speeds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "radeon_exporter_freq1_input{card_id=\"$cardID\"} ",
     "legendFormat": "gfx/compute clock"
    },
    {
     "expr": "radeon_exporter_freq2_input{card_id=\"$cardID\"} ",
     "legendFormat": "memory clock"
    }
   ]
  },
  {
   "title": "GTT Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "radeon_exporter_mem_info_gtt_total{card_id=\"$cardID\"} ",
     "legendFormat": "GTT Total"
    },
    {
     "expr": "radeon_exporter_mem_info_gtt_used{card_id=\"$cardID\"} ",
     "legendFormat": "GTT Used"
    }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "radeon_exporter_fan1_input{card_id=\"$cardID\"}",
     "legendFormat": "Fan Speed"
    },
    {
     "expr": "radeon_exporter_fan1_max{card_id=\"$cardID\"}",
     "legendFormat": "Fan Max Speed"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "radeon_exporter_power1_average{card_id=\"$cardID\"} / 1000",
     "legendFormat": "Fan Speed"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "radeon_exporter_temp1_input{card_id=\"$cardID\"} / 1000",
     "legendFormat": "GPU die temperature"
    },
    {
     "expr": "avg_over_time(radeon_exporter_temp1_input{card_id=\"$cardID\"}[30m]) / 1000",
     "legendFormat": "30m Moving Avg"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "radeon_exporter_in0_input{card_id=\"$cardID\"} ",
     "legendFormat": "GPU voltage"
    }
   ]
  }
 ]
}